# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='twiBay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit_id', models.DecimalField(decimal_places=0, max_digits=30)),
                ('twit', models.CharField(max_length=300)),
                ('twit_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='twiCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit_id', models.DecimalField(decimal_places=0, max_digits=30)),
                ('twit', models.CharField(max_length=300)),
                ('twit_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='twiDra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit_id', models.DecimalField(decimal_places=0, max_digits=30)),
                ('twit', models.CharField(max_length=300)),
                ('twit_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='twiGia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit_id', models.DecimalField(decimal_places=0, max_digits=30)),
                ('twit', models.CharField(max_length=300)),
                ('twit_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='twiSwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit_id', models.DecimalField(decimal_places=0, max_digits=30)),
                ('twit', models.CharField(max_length=300)),
                ('twit_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='twiTig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit_id', models.DecimalField(decimal_places=0, max_digits=30)),
                ('twit', models.CharField(max_length=300)),
                ('twit_at', models.DateTimeField()),
            ],
        ),
    ]
