# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='twitChu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='twitYaku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.CharField(max_length=300)),
            ],
        ),
    ]
