# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfan_001', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitbay',
            old_name='twit_user_id',
            new_name='twit_id',
        ),
        migrations.RenameField(
            model_name='twitcar',
            old_name='twit_user_id',
            new_name='twit_id',
        ),
        migrations.RenameField(
            model_name='twitdra',
            old_name='twit_user_id',
            new_name='twit_id',
        ),
        migrations.RenameField(
            model_name='twitgia',
            old_name='twit_user_id',
            new_name='twit_id',
        ),
        migrations.RenameField(
            model_name='twitswa',
            old_name='twit_user_id',
            new_name='twit_id',
        ),
        migrations.RenameField(
            model_name='twittig',
            old_name='twit_user_id',
            new_name='twit_id',
        ),
    ]
