# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfan_001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='twitHan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='twitHiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='twitKyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='twitYoko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.CharField(max_length=300)),
            ],
        ),
    ]
