# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfan_001', '0002_twithan_twithiro_twitkyo_twityoko'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='twitYaku',
            new_name='twitBay',
        ),
        migrations.RenameModel(
            old_name='twitHiro',
            new_name='twitCar',
        ),
        migrations.RenameModel(
            old_name='twitYoko',
            new_name='twitDra',
        ),
        migrations.RenameModel(
            old_name='twitChu',
            new_name='twitGia',
        ),
        migrations.RenameModel(
            old_name='twitHan',
            new_name='twitSwa',
        ),
        migrations.RenameModel(
            old_name='twitKyo',
            new_name='twitTig',
        ),
    ]
